### ISSUE TITLE
Remove X-Precise from XH Generator

### ISSUE THREAD

**Issue by luboskmetko** [xhtmlized/generator-xh#101]
Based on our survey results X-Precise should be removed from generator to allow different workflows.

`xprecise` folder which was used for storing design overlays should be preserved but renamed to more generic `designs`

**Comment by piotrkulpinski** [comment]
Hi guys, 
I think it'd be good idea to remove this directory totally from generator. I don't think anyone use it and I even saw some people using it as 'media' folder when they put project content images there. So I guess it can be confusing as well.

Let me know what you think. @luboskmetko @thymikee

**Comment by thymikee** [comment]
Agreed :+1:

**Comment by luboskmetko** [comment]
I agree too. It comes from the times when it was useful to have original source file for sprites but with automatic sprites generation, it's useless.
