### ISSUE TITLE
Set box-sizing to border-box in common styles

### ISSUE THREAD

**Issue by yuijim** [xhtmlized/generator-xh#119]
I seemed to add this in all the projects I've been working on during last few months. Maybe we should run the survey and bring it into generator as default if majority would like that?

**Comment by piotrkulpinski** [comment]
I totally agree! :) 
Although, if we were to implement this into base styles I'd go with "inherited" border-box property which allows you to easily change it in the future if there's such need.

More info about this here: http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by yuijim** [comment]
That's pretty neat trick, @piotrkulpinski, thanks for sharing - I think I will implement it that way (as the survey got 100% in favour of border-box).
