### ISSUE TITLE
Consider adding icomoon automation

### ISSUE THREAD

**Issue by X-Aleks** [xhtmlized/generator-xh#127]
__Task could watch for adding icomoon.zip package and do following tasks:__

* unzip package
* replace default paths while copying styles
* copy fontfiles to appropriate folder
* clean up unnecessary files and zip package itself

__Useful grunt tasks:__
  * grunt-zip
  * grunt-contrib-copy
  * grunt-text-replace
  * grunt-contrib-clean

**Comment by piotrkulpinski** [comment]
Hi @X-Aleks 
I have created the external package for that task: https://www.npmjs.com/package/grunt-icomoon-zip
But I'm wondering if it wouldn't be better option to create a task that would look at your `icons` directory for svg files and automatically create iconfont for that?
This way each contributor could easily see what icons are used in the project as they would sit in the project repository.
Let me know what you think.
