### ISSUE TITLE
Change the way includereplace & usemin works

### ISSUE THREAD

**Issue by yuijim** [xhtmlized/generator-xh#134]
It happens that build process fails and backup include files aren't restored correctly, which often goes unnoticed till later and forces user to revet those files to previous versions (not to mention that project breaks).

**Comment by piotrkulpinski** [comment]
In addition to that, I've noticed that each time I save a html file, a new set of files is added to concat:generated array: https://www.dropbox.com/s/0ziajz3rie2c60w/Screenshot%202015-02-03%2011.08.32.png?dl=0

This is increasing the build time dramatically when you have grunt task running for a long time.
