### ISSUE TITLE
Adding new options

### ISSUE THREAD

**Issue by thymikee** [xhtmlized/generator-xh#140]
How do you feel about adding new options to generator?

For now we have:
* Should XHTMLized branding be used?
* Which type of live reloader would you like to use?
* Do you want to run development server? 
* Which CSS preprocessor would you like to use? 
* Add dist folder to the Git ignore list? 
* Is this WordPress project?
* Select additional features: 

Should new options be added as a questions, or maybe as additional features? Feel free to discuss this matter.

**Comment by luboskmetko** [comment]
@thymikee since there is no feedback on this currently, can we close it? 

Trying to clean up issues a bit. Thanks
