### ISSUE TITLE
Do not link XHTMLized logo to legacy server

### ISSUE THREAD

**Issue by arekf** [xhtmlized/generator-xh#143]
We've noticed that you are linking XHTMLized logo for branded projects to http://email-static.xhtmlized.com/images/logo.png.

This is legacy server and it will be turned off soon, so please move it as soon as possible.

**Comment by piotrkulpinski** [comment]
We can change that, but please keep in mind that all of previous projects will still be using the old url.

**Comment by ajgon** [comment]
If we don't change it, new projects also will be using the old url :smirk_cat: 
Please fix it, I'll take care of the old projects.

**Comment by piotrkulpinski** [comment]
What is the new url then?
