### ISSUE TITLE
LESS compiling error

### ISSUE THREAD

**Issue by bagahunda** [xhtmlized/generator-xh#159]
When i choose LESS as css preprocessor and try to create new page i've got this error:

Running "less:dist" (less) task
>> NameError: variable @sprite is undefined in src/less/setup/sprites.less on line 9, column 11:
>> 8 .sprite-retina($sprite, $sprite2x) {
>> 9   .sprite(@sprite);
>> 10   .sprite-background-size(@sprite);
Warning: Error compiling src/less/main.less Use --force to continue.

Aborted due to warnings.

**Comment by piotrkulpinski** [comment]
@bagahunda Thanks for reporting that. We'll look into it and let you know.

**Comment by luboskmetko** [comment]
@thymikee can you verify if this was fixed?
