### ISSUE TITLE
Timestamps and TOC updated only on grunt build

### ISSUE THREAD

**Issue by luboskmetko** [xhtmlized/generator-xh#165]
I've noticed @@timestamp and @@toc are only updated on grunt build but not when running watch tasks. This means that unless grunt build is run afterwards you will end with these placeholders. Is this intentional? Thanks

**Comment by thymikee** [comment]
As far as I can tell, this is intentional, as `grunt build` runs every time a commit is deployed to previewized server.

**Comment by luboskmetko** [comment]
Thanks!
