### ISSUE TITLE
Option to toggle imagemin, svg2png, spritesmith & remfallback

### ISSUE THREAD

**Issue by phuclb** [xhtmlized/generator-xh#168]
These are good dependencies, but I think we should have option to toggle them when building generator. They are not cool for me.

**Comment by luboskmetko** [comment]
@thymikee thinking this can be a good suggestion and related to your question about additional options. Maybe we could have this as prechecked options?

**Comment by thymikee** [comment]
I believe this is good solution. What's important, it won't break current workflow. @piotrkulpinski, what do you think?

**Comment by piotrkulpinski** [comment]
I agree, keeping it as 'optional' sounds good. Sometimes it bothers me that I can't disable it during project generation and image optimisation is not always wanted.

**Comment by arturkot** [comment]
I'm good with such update as well. It's connected with this one btw: https://github.com/xhtmlized/generator-xh/issues/173
