### ISSUE TITLE
JS are not compiled when a JS (main.js) is updated

### ISSUE THREAD

**Issue by phuclb** [xhtmlized/generator-xh#169]
When I'm working with main.js, the generator just update this file only with jshint and stop building other libraries into compressed files, that's why page gets errors when reloaded.

I have to rebuild all (grunt build) to make it works as it should be, everytime I make a change in main.js.

**Comment by luboskmetko** [comment]
@thymikee can you please verify this? Thanks

**Comment by thymikee** [comment]
@phuclb, what do you mean by "stop building other libraries into compressed files"? Can you describe more thoroughly? Thanks!

**Comment by phuclb** [comment]
it means when we build several js files into ones automatically, it won't do this step when other js file (main.js) is changed, event grunt watch is running. And then we have to grunt build again for that.

**Comment by piotrkulpinski** [comment]
Hi Phuc,
The JS concatenation is done using usemin grunt plugin and it's only running when you save the html files on watch. We don't run it on JS/CSS save event as it would drastically slow the watch process for those files.

Also, I believe that JS concatenation is mostly used for bower/external components which are not watched by watch process. If you need concatenate your local files just update your grunt/contrib-watch.js file with that change: 

```
js: {
  files: ['<%= xh.src %>/js/*.js'],
  tasks: ['build-html', 'build-js']
}
```
I don't see us adding the feature for production version of generator.
