### ISSUE TITLE
Remfallback trips on bootstrap-sass-official 3.3.5

### ISSUE THREAD

**Issue by arturkot** [xhtmlized/generator-xh#173]
Hello,

just a warning. I've discovered that in one of my projects the package wasn't successfully built. It's turned that remfallback doesn't wan't to cooperate with the latest Bootstrap...

Steps to reproduce:
1. Makes sure you've got grunt-remfallback  0.0.5 installed
2. Make sure there's bootstrap-sass-official 3.3.5 installed (latest one)
3. Try to build the project with following imports from Sass:
  * @import "bootstrap-sass-official/assets/stylesheets/bootstrap/variables";
  * @import "bootstrap-sass-official/assets/stylesheets/bootstrap/mixins";
  * @import "bootstrap-sass-official/assets/stylesheets/bootstrap/utilities";
  * @import "bootstrap-sass-official/assets/stylesheets/bootstrap/responsive-utilities";
  * @import "bootstrap-sass-official/assets/stylesheets/bootstrap/grid";
  * @import "bootstrap-sass-official/assets/stylesheets/bootstrap/component-animations";

Cheers,

Artur

PS.
grunt-remfallback hasn't been udpated for about 1 year. Not a good sign.

**Comment by luboskmetko** [comment]
@arturkot thanks, Artur. Do you suggest to remove the package completely? Haven't found any up-to-date alternative.

**Comment by arturkot** [comment]
Hey @luboskmetko ,

I guess we'd need to ask around. As for me – it can go away, I don't really use it. I know that many other people do, though. Perhaps it would be the best to make it optional? It might also be that this bug is only valid for BS 3.3.5 and it'll be fixed on their end?

More questions than answers. :)

Cheers,

Artur

**Comment by thymikee** [comment]
Guys, how about removing remfallback entirely from generator? 
[Support of rem units is pretty good](http://caniuse.com/#feat=rem). 

Or we can leave it as an option (non default) and put in the `grunt:build` task.

The main reason for all of this is a fact, that removing `remfallback` task speeds up my current watch build 3-5x...

**Comment by luboskmetko** [comment]
I've just started experimenting with ITCSS for our new website (so far it looks pretty good) and Harry Roberts is using this font-size mixing https://github.com/csswizardry/frcss/blob/master/_tools.mixins.scss which also generates px fallbacks for rem values. Maybe an alternative?

**Comment by piotrkulpinski** [comment]
I'm gonna migrate autoprefixer to use it as postcss plugin, so we may use one of the other extensions to fallback rems, like this one: https://github.com/robwierzbowski/node-pixrem

That being said, I don't think we still need to fallback rems, as like @thymikee said, they're pretty well supported nowadays.
