### ISSUE TITLE
Replace grunt-autoprefixer with grunt-postcss

### ISSUE THREAD

**Issue by luboskmetko** [xhtmlized/generator-xh#174]
https://github.com/nDmitry/grunt-autoprefixer was deprecated in favor of https://github.com/nDmitry/grunt-postcss

Btw. I was only able to generate working source map when generating source map in sass.js and also in PostCSS

**Comment by piotrkulpinski** [comment]
Fixed in be418f55c34cc283d74d9c13b630de3fa52beb5b
