### ISSUE TITLE
Fatal error: Cannot read property 'contents' of undefined during tasks newer:imagemin:nosvg and imagemin:sprites

### ISSUE THREAD

**Issue by pbdev-pl** [xhtmlized/generator-xh#194]
Hi guys, recently I run into problem with building XH Generator WP project. I have updated 32bit version of node to version 5.0 and other required by XH generator packages to recent versions. I am using Windows 7 x64.

First problem is with imagemin:nosvg task it produces error:
Fatal error: Cannot read property 'contents' of undefined
I fixed it by updating grunt-contrib-imagemin to version 1.0

Second one is in task imagemin:sprites, I got the same error:
Fatal error: Cannot read property 'contents' of undefined

I fixed it changing line 51 in file grunt/contrib-imagemin.js from:
src: ['img/common/{sprites,sprites@2x}.png'],
to:
src: ['/img/common/{sprites,sprites@2x}.png'],

If the fixes are correct, could someone include them in future versions?

**Comment by piotrkulpinski** [comment]
Hi @pbdev-pl 
We're experiencing the same issues but it's not caused by the generator itself but one of imagemin dependency packages. The only option is to wait for it to be fixed so in the meantime you can disable those tasks by commenting them out in buildhelpers.js file and enable assets copying by removing the second array property here: https://github.com/xhtmlized/generator-xh/blob/master/app/templates/grunt/contrib-copy.js#L16

Thanks, Piotrek

**Comment by pbdev-pl** [comment]
The second error can by easly fixed by adding "/" before "img" in contrib-imagemin.js file like so:
src: ['/img/common/{sprites,sprites@2x}.png'],

I think it does not depend on imagemin, just the path is wrong because:
cwd is set to <%= xh.dist %> which is in fact path to "dist" folder, when you combine it with old path img/common/{sprites,sprites@2x}.png you get:
distimg/common/{sprites,sprites@2x}.png
instead of
dist/img/common/{sprites,sprites@2x}.png

Am I right?

**Comment by piotrkulpinski** [comment]
I don't think that's the issue 'cause grunt tasks use `path.join` function which takes care of that.
I'll take a look at it tomorrow, but definitely seems like it's one of the deps causing that as we didn't change anything recently.

**Comment by pbdev-pl** [comment]
Anyway the path change fixed my problem, without that I could not finish sprite task.
