### ISSUE TITLE
Support for HTML Emails projects

### ISSUE THREAD

**Issue by luboskmetko** [xhtmlized/generator-xh#24]

**Comment by piotrkulpinski** [comment]
Hi guys, 
What do you think about creating a separate xh generator for email projects?
I think it would be better as usually email templates are created as a separate project and there's no need to clutter our existing tool.

It could be named generator-xh-email to keep consistency and keep our name in the tool.
What do you think @luboskmetko @thymikee @yuijim ?

**Comment by luboskmetko** [comment]
@piotrkulpinski sounds good to me

**Comment by yuijim** [comment]
@piotrkulpinski yeah, keeping it separate definitely sounds good

**Comment by piotrkulpinski** [comment]
As agreed, further development of this part will be done on a separate repo here: https://github.com/xhtmlized/generator-xh-email

**Comment by piotrkulpinski** [comment]
Hi guys,
I've migrated my code to the https://github.com/xhtmlized/generator-xh-email repository and adjusted the code to be in sync with main generator.
I would love it you'd find some time to test the new email generator and give some feedback. Maybe it lacks some important functionalities or you think we should improve some parts.

Thanks!
