### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by luboskmetko** [xhtmlized/generator-xh#6]

**Comment by luboskmetko** [comment]
Changing this to Browserify which we've already used in some projects.

**Comment by piotrkulpinski** [comment]
I think we may also consider implementing https://github.com/webpack/webpack as it's getting more and more popular nowadays. We could add this as an option to choose browserify/webpack.

**Comment by luboskmetko** [comment]
Yeah, that would be nice depending on how much additional time it would take. The issue is that if you want to develop JS in modular way with our generator nowadays, you need to set it up yourself and that setup isn't that straightforward (at least from what I heard about using Browserify with our generator). 

So would be great if we give users some options (one of them even could be to use current setup). Changed the priority of this to medium.

**Comment by thymikee** [comment]
I have working setup of Browserify with our generator (isn't straightforward) so I could take that task. I see it as one of the options next to Modernizr, Bootstrap, etc.

**Comment by piotrkulpinski** [comment]
@thymikee that would be great! Let's add it under 'Additional features' as you proposed.
